theme: jekyll-theme-architect

# Site Settings
locale                   : "en-US"
title                    : "Haocheng Li"
title_separator          : "-"
name                     : "Haocheng Li"
description              : "Software Engineering Intern at Cadence Design Systems"
url                      : "https://haocheng.li"

# Site Author
author:
  name             : "Haocheng Li"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  twitter          : Rholais

plugins:
  - jekyll-seo-tag
  
