theme: jekyll-theme-architect

# Site Settings
locale                   : "en-US"
title                    : "Haocheng Li"
title_separator          : "-"
name                     : "Haocheng Li"
description              : "Software Engineering Intern at Cadence Design Systems"
url                      : "https://haocheng.li"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "Rholais/Rholais.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"

# Site Author
author:
  name                   : "Haocheng Li"
  avatar                 : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
